#!/bin/bash

export UNIX_SYSTEM_NAME=$(uname -s)
export NUMBER_OF_CPU_CORES=$(grep -c ^processor /proc/cpuinfo)
export READLINK=readlink

INSTALL_ROOT_RELATIVE="../libBLS/deps/deps_inst/x86_or_x64/"
INSTALL_ROOT=$($READLINK -f $INSTALL_ROOT_RELATIVE)

TOP_CMAKE_BUILD_TYPE="RelWithDebInfo"
DEBUG_D=""

git clone https://github.com/skalenetwork/libjson-rpc-cpp.git --recursive
cd libjson-rpc-cpp
git checkout 245a2b73276cdd99a3f5b262a5aad1c86ef227a5
git pull
rm -rf build || true
mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT -DCMAKE_BUILD_TYPE=$TOP_CMAKE_BUILD_TYPE \
	-DBUILD_SHARED_LIBS=NO \
	-DBUILD_STATIC_LIBS=YES \
	-DUNIX_DOMAIN_SOCKET_SERVER=YES \
	-DUNIX_DOMAIN_SOCKET_CLIENT=YES \
	-DFILE_DESCRIPTOR_SERVER=YES \
	-DFILE_DESCRIPTOR_CLIENT=YES \
	-DTCP_SOCKET_SERVER=YES \
	-DTCP_SOCKET_CLIENT=YES \
	-DREDIS_SERVER=NO \
	-DREDIS_CLIENT=NO \
	-DHTTP_SERVER=YES \
	-DHTTP_CLIENT=YES \
	-DCOMPILE_TESTS=NO \
	-DCOMPILE_STUBGEN=YES \
	-DCOMPILE_EXAMPLES=NO \
	-DWITH_COVERAGE=NO \
	-DARGTABLE_INCLUDE_DIR=../../../libBLS/deps/argtable2/src \
	-DARGTABLE_LIBRARY=$INSTALL_ROOT/lib/libargtable2${DEBUG_D}.a \
	-DCURL_INCLUDE_DIR=$INSTALL_ROOT/include \
	-DJSONCPP_INCLUDE_DIR=$INSTALL_ROOT/include \
	..
make -j $NUMBER_OF_CPU_CORES
make -j $NUMBER_OF_CPU_CORES install
cd ../..