version: '3'
services:
  sgxwallet:
    image: skalenetwork/sgxwallet_release:1.9.0-stable.2
    restart: unless-stopped
    network_mode: host
    devices:
      - "/dev/isgx"
      - "/dev/mei0"
    volumes:
      - ./sgx_data:/usr/src/sdk/sgx_data
      -  /dev/urandom:/dev/random
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"
    command: -y -d -e
    healthcheck:
      test: ["CMD", "ls", "/dev/isgx", "/dev/mei0"]

