name: Build and push release SGX container
on:
  workflow_dispatch:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SECRET_KEY: ${{ secrets.V2 }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Fail, if older Github Actions machine. Click "Re-run jobs"
        run: cat /proc/cpuinfo | grep avx512
      - name: Login to docker
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - uses: actions/checkout@v2
      - name: Submodule update
        run: git submodule update --init --recursive
      
      # Host build steps (moved from DockerfileBase)
      - name: Install host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends \
            wget \
            curl \
            git \
            build-essential \
            cmake \
            apt-utils \
            vim \
            telnet \
            ca-certificates \
            perl \
            alien \
            uuid-dev \
            libxml2-dev \
            ccache \
            yasm \
            libprocps-dev \
            texinfo \
            graphviz \
            doxygen \
            libgnutls28-dev \
            libgcrypt20-dev
          chmod +x scripts/install_packages.sh
          sudo ./scripts/install_packages.sh
      
      - name: Install libssl1.1 dependency
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          rm -f libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      
      - name: Install Intel SGX SDK and PSW
        run: |
          git clone -b sgx_2.25 --depth 1 https://github.com/intel/linux-sgx
          cd linux-sgx
          make preparation -j$(nproc)
          make sdk_install_pkg_no_mitigation -j$(nproc)
          WORK_DIR=$(pwd)
          sudo mkdir -p /opt/intel
          cd /opt/intel
          sudo sh -c 'echo yes | $WORK_DIR/linux/installer/bin/sgx_linux_x64_sdk_*.bin'
          cd $WORK_DIR
          make psw_install_pkg -j$(nproc)
          cd /opt/intel
          sudo cp $WORK_DIR/linux/installer/bin/sgx_linux_x64_psw*.bin .
          sudo ./sgx_linux_x64_psw*.bin --no-start-aesm
          sudo rm -f sgx_linux_x64_psw*.bin
          cd $WORK_DIR/..
          rm -rf linux-sgx

      - name: Setup ccache
        run: |
          sudo ln -sf /usr/bin/ccache /usr/local/bin/clang
          sudo ln -sf /usr/bin/ccache /usr/local/bin/clang++
          sudo ln -sf /usr/bin/ccache /usr/local/bin/gcc
          sudo ln -sf /usr/bin/ccache /usr/local/bin/g++
          sudo ln -sf /usr/bin/ccache /usr/local/bin/cc
          sudo ln -sf /usr/bin/ccache /usr/local/bin/c++
      
      - name: Build dependencies
        run: |
          cd scripts
          sudo ./build_deps.py
      
      - name: Install Intel DAL Host Interface
        run: |
          cd scripts
          wget --progress=dot:mega -O - https://github.com/intel/dynamic-application-loader-host-interface/archive/072d233296c15d0dcd1fb4570694d0244729f87b.tar.gz | tar -xz
          cd dynamic-application-loader-host-interface-072d233296c15d0dcd1fb4570694d0244729f87b
          cmake . -DCMAKE_BUILD_TYPE=Release -DINIT_SYSTEM=SysVinit
          make install -j$(nproc)
          cd ..
          rm -rf dynamic-application-loader-host-interface-072d233296c15d0dcd1fb4570694d0244729f87b
      
      - name: Create dir for signing enclave
        run: mkdir signed_enclaves
      - name: Write secret to file
        run: 'echo "$SECRET_KEY" > signed_enclaves/skale_sgx_private_key0.pem'
        shell: bash
      - name: Generate public key
        run: openssl rsa -in signed_enclaves/skale_sgx_private_key0.pem -pubout -out signed_enclaves/skale_sgx_public_key0.pem
      
      - name: Configure and build SGX wallet for release
        run: |
          source /opt/intel/sgxsdk/environment
          cp -f secure_enclave/secure_enclave.config.xml.release secure_enclave/secure_enclave.config.xml
          ./autoconf.bash
          ./configure --with-sgx-build=release
          cd secure_enclave
          make secure_enclave.so -j$(nproc)
          cd ../scripts
          ./sign_enclave.bash
          cd ..
          rm /usr/src/sdk/secure_enclave/secure_enclave*.so
          cp signed_enclaves/secure_enclave_signed0.so secure_enclave/secure_enclave.signed.so
          make -j$(nproc)
          mkdir -p sgx_data
      
      - name: Calculate and cache VERSION
        run : |
          export BRANCH=${GITHUB_REF##*/}
          echo "Branch $BRANCH"
          export CURRENT_VERSION=$(cat VERSION)
          echo "Current Version $CURRENT_VERSION"
          export NEW_VERSION=$(bash ./scripts/calculate_version.sh $BRANCH $CURRENT_VERSION)
          echo "New Version $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      - name: Update VERSION file
        run : |
          echo "Updating VERSION file with $VERSION"
          echo "$VERSION" > VERSION
      - name: Build and deploy docker image
        env:
          VERSION: ${{ env.VERSION }}
          BRANCH: ${{ env.BRANCH }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run : |
          echo "Branch $BRANCH"
          echo "Using cached version $VERSION"
          export RELEASE=true
          echo "::set-env name=RELEASE::$RELEASE"
          bash ./scripts/build_image.sh DockerfileRelease sgxwallet_release
          bash ./scripts/publish_image.sh sgxwallet_release
      - name: Delete secrets
        run: rm -f signed_enclaves/skale_sgx_private_key0.pem signed_enclaves/skale_sgx_public_key0.pem
      - name: Copy secure_enclave.signed.so
        run: |
          export IMAGE_NAME=skalenetwork/sgxwallet_release:$VERSION
          docker create --name extract $IMAGE_NAME
          docker cp extract:/usr/src/sdk/secure_enclave/secure_enclave.signed.so signed_enclaves/secure_enclave_signed.so
          docker rm extract
      - name: Check signed enclaves dir
        run: ls signed_enclaves
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
      - name: Upload signed enclave to Release
        uses: actions/upload-release-asset@latest
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: signed_enclaves/secure_enclave_signed.so
          asset_name: signed_enclave.so
          asset_content_type: application/octet-stream
