name: Build and push SGX container
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Fail, if older Github Actions machine. Click "Re-run jobs"
        run: cat /proc/cpuinfo | grep avx512
      - name: Login to docker
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - uses: actions/checkout@v2
      - name: submodule update
        run: git submodule update --init --recursive
      - name: build and deploy test image
        run: python3 scripts/docker_build.py Dockerfile sgxwallet ${GITHUB_SHA}
      - name: Calculate and cache VERSION
        if: |
          github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/beta' ||
          github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/SECURE_ENCLAVE_CHANGES'
        run : |
          export BRANCH=${GITHUB_REF##*/}
          echo "Branch $BRANCH"
          export CURRENT_VERSION=$(cat VERSION)
          echo "Current Version $CURRENT_VERSION"
          export NEW_VERSION=$(bash ./scripts/calculate_version.sh $BRANCH $CURRENT_VERSION)
          echo "New Version $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      - name: Update VERSION file
        if: |
          github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/beta' ||
          github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/SECURE_ENCLAVE_CHANGES'
        run : |
          echo "Updating VERSION file with $VERSION"
          echo "$VERSION" > VERSION
      - name: deploy docker image
        env:
          VERSION: ${{ env.VERSION }}
          BRANCH: ${{ env.BRANCH }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        if: |
          github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/beta' ||
          github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/SECURE_ENCLAVE_CHANGES'
        run : |
          echo "Branch $BRANCH"
          echo "Using cached version $VERSION"
          export RELEASE=true
          echo "::set-env name=RELEASE::$RELEASE"
          bash ./scripts/build_image.sh Dockerfile sgxwallet
          bash ./scripts/publish_image.sh sgxwallet
      - name: Create Release
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: true

