name: Build base container
on:
  workflow_dispatch:
  push:
    tags:
      - build_base*
jobs:
  build:
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_UNSECURE_COMMMANDS: true
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Fail, if older Github Actions machine
      run: cat /proc/cpuinfo | grep avx512
    - name: Login to docker
      run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - uses: actions/checkout@v2
    - name: Submodules (prove they are correct)
      run: |
        set -euxo pipefail
        git submodule sync --recursive
        git submodule update --init --recursive
        git submodule status --recursive
        git -C libBLS rev-parse HEAD
        git -C sgx-gmp rev-parse HEAD

    - name: Build the Docker image
      run: docker build --no-cache --pull . --file DockerfileBase --tag skalenetwork/sgxwallet_base:build_2026_01_19 && docker push skalenetwork/sgxwallet_base:build_2026_01_19
